[package]
name = "rusty_game"
version = "0.1.0"
edition = "2021"

[profile.dev]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
incremental = false
codegen-units = 16

[dependencies]
rusty_engine = "5.2.1"



